# Generated by Django 2.2.6 on 2019-10-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApacheLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.GenericIPAddressField(verbose_name='IP address')),
                ('time', models.DateTimeField(verbose_name='Time')),
                ('method', models.CharField(max_length=10, verbose_name='HTTP method')),
                ('url', models.URLField(verbose_name='URL')),
                ('status', models.CharField(max_length=3, verbose_name='Status')),
                ('size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Size')),
            ],
            options={
                'verbose_name': 'Apache log',
                'verbose_name_plural': 'Apache log',
            },
        ),
        migrations.AddIndex(
            model_name='apachelog',
            index=models.Index(fields=['host', 'time', 'method'], name='apachelog_a_host_1c170f_idx'),
        ),
    ]
